# Generated by Django 4.2.10 on 2024-08-16 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='amount_of_students',
        ),
        migrations.AddField(
            model_name='group',
            name='max_students',
            field=models.IntegerField(default=30, verbose_name='Максимальное количество студентов'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
